### ISSUE TITLE
Difference between overriding and polymorphism

### ISSUE THREAD

**Issue by jltha** [nus-cs2113-AY2122S2/forum#11]
Is overriding an implementation of polymorphism, or are they different in their uses? What differentiates between the two when we apply them in the code?

**Comment by okkhoy** [comment]
Are you by any chance talking about overloading (and not overriding as you mention above)?

Overriding _is a_ mechanism to achieve polymorphism.
You name a behavior (i.e., method name) and define different behaviors in the class hierarchy (needs substitutability, i.e., inheritance in play). 
Now when you invoke the behavior using the parent class reference, the actual behavior shown (i.e., the method executed) depends on the object, not the reference used for invoking. Thus, using a parent class reference and invoking a behavior by name, you are getting different behaviors from the sub-classes.

A classical example of making animals talk:
Name of the behavior: `speak` in Animal class.
Behaviors defined: 
Dog `speak` -> `woof woof` (Dog **is a** Animal)
Cat `speak` -> `meow`   (Cat **is a** Animal)

So invoked behavior: `speak`
Obtained behavior: `woof woof` or `meow` depending on the underlying object.

**Comment by jltha** [comment]
Hi Prof, no I was asking about overriding as I was unsure whether it directly leads to polymorphism. But thank you for the clarification!
