### ISSUE TITLE
Invitation link doesn't work

### ISSUE THREAD

**Issue by eigne** [nus-cs2113-AY2122S2/forum#12]
https://github.com/orgs/nus-cs2113-AY2122S2/invitation

Trying to open this link gives me this:

![image](https://user-images.githubusercontent.com/60597985/151584969-fee18382-588f-46d0-b088-23b27af21f5e.png)

But as I see this:

![image](https://user-images.githubusercontent.com/60597985/151585113-e7d69384-ae77-475d-9f41-a3ddc0159789.png)

on https://github.com/nus-cs2113-AY2122S2 I assume I am not already part of the org.

**Comment by okkhoy** [comment]
Yup. We haven't sent it yet. I am still collating information from the students who haven't submitted github usernames. Will announce when it is ready.

**Comment by eigne** [comment]
Thank you.
