### ISSUE TITLE
Coursemology Week 4 Question 3

### ISSUE THREAD

**Issue by tanweili** [nus-cs2113-AY2122S2/forum#13]
For the public test cases I am able to pass for the expression "Main.main(args)(Verify)" but not for the expression "Main.main(args)" and it's giving me NullPointerException. What's the difference between these two test cases regarding the "(verify)"?

**Comment by okkhoy** [comment]
@Mick609 @shivin9 can you please take a look and help?

**Comment by khseah** [comment]
Are you using a For-Each loop to loop through the shapes array by any chance? Since we initialized an array of size 100 but only added 4 shapes, the NullPointerException error will be encountered when the loop iterates to the 5th element in the shapes array.

**Comment by tanweili** [comment]
Yes this appears to be the problem. Managed to do a primitive workaround for it. Thanks for the insight!
