### ISSUE TITLE
Accidentally delete the ip repository

### ISSUE THREAD

**Issue by tuan0369** [nus-cs2113-AY2122S2/forum#16]
So while playing around with github I accidentally deleted my ip repository and according to google it seems like I cannot restore that repository. Does that mean the pull request I created is lost? Can I just fork and upload everything again? Is there any mark deduction for this since my ip will only have uploading record from this week?

**Comment by okkhoy** [comment]
Fork again and push all changes to the new fork.
Close your earlier PR (if it is still around) and create another PR.
Should not affect you (much) in terms of marks. Please do the remaining tasks on time, correctly; you will be safe then.

**Comment by tuan0369** [comment]
ok thank you!
