### ISSUE TITLE
Level-2 missing from commits but visible under tags. Does this matter?

### ISSUE THREAD

**Issue by eigne** [nus-cs2113-AY2122S2/forum#19]
My repo's commits look messy:
![image](https://user-images.githubusercontent.com/60597985/151788897-c8e75fd2-67b1-4580-af52-d0b97729365f.png)
and the "Level-2" tag is missing. However my tags look fine:
![image](https://user-images.githubusercontent.com/60597985/151789004-d46efe64-00e5-4da7-a462-bbb3b6e29db2.png)
Should I be worried that the Level-2 commit is missing? I checked the iP dashboard at https://nus-cs2113-ay2122s2.github.io/dashboards/contents/ip-progress.html and I received credit for Level-2 so I assume there aren't any issues with this but I wanted to make sure.

**Comment by okkhoy** [comment]
Should be fine. But please try to do it the right way going forward.

**Comment by eigne** [comment]
Thank you.
