### ISSUE TITLE
Error creating repository in Sourcetree

### ISSUE THREAD

**Issue by BradenTeo** [nus-cs2113-AY2122S2/forum#2]
I tried following the steps to create a repo in [W2.7c](https://nus-cs2113-ay2122s2.github.io/website/schedule/week2/topics.html#W2-7c ), but resulted in this error:
![image](https://user-images.githubusercontent.com/58351701/150624638-2fae8dff-a695-4b8b-ae66-a96572236137.png)

I can use Git CLI, but since the lectures use Sourcetree, I would like to use that instead. Any suggestions to resolve this issue?

Thank you.

**Comment by eigne** [comment]
Have you tried switching from embedded git to system git (or vice versa)? The options to do so are at Tools -> Options -> Git -> Git version. Mine looks like this and seems to work fine.
![image](https://user-images.githubusercontent.com/60597985/150627876-0047da1b-8cec-4c8d-9b36-9e7ceb12ecbb.png)

**Comment by okkhoy** [comment]
Does the folder c:\Users\bteow\gittest3 exist? From my experience, if the folder is not present Sourcetree **won't** create it.

Also, it is not mandatory to use Sourcetree. If you are comfortable with the Git CLI you can use it (you can embed a terminal/gitbash within IntelliJ and use it).

**Comment by BradenTeo** [comment]
Thank you both! I switched to embedded git and it works. And I didn't know a folder has to be created first, thanks!
