### ISSUE TITLE
SourceTree indefinite waiting time when pushing

### ISSUE THREAD

**Issue by GlendonNotGlen** [nus-cs2113-AY2122S2/forum#20]
Hii, I've had no issues with earlier commits and pushing but it seems like after I've requested the upstream pull request yesterday, I am unable to perform a Push (no issues with staging). I have not changed any settings between then and now so I am quite puzzled about what could be the reason for this issue.

![image](https://user-images.githubusercontent.com/86562428/151921628-aed77a3d-22df-4130-8b2d-6a919c30e475.png)

**Comment by okkhoy** [comment]
Hard to say without knowing what is happening behind the scene.
Pls check "show full output" and paste the output here.
Additionally, try git push on the command line/terminal, do you see the same behavior?

**Comment by GlendonNotGlen** [comment]
> Hard to say without knowing what is happening behind the scene. Pls check "show full output" and paste the output here. Additionally, try git push on the command line/terminal, do you see the same behavior?

For the full output it is as below:
git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks push -v --tags origin master:master

For performing git push on command line/ should i just type git push with no flags? Sorry I'm not too familiar with using git on CLI

**Comment by okkhoy** [comment]
Yup, just use `git push` in the directory where you have cloned the iP from your account.

This output is not very useful as it just shows the command and nothing in the response.

**Comment by GlendonNotGlen** [comment]
I've tried the `git push` using CLI and it was similarly loading with no error messages or warnings - which led me to believe that the problem was with my Git rather than SourceTree. After updating my Git to the latest version, I am able to successfully push with no issues. 

Thanks, Prof!

**Comment by okkhoy** [comment]
Ouch! That was quite puzzling to me 😕 
Glad that you got it working 🎉 🎉
