### ISSUE TITLE
(iP) Expected Behaviour of Chatbot when Adding Tasks

### ISSUE THREAD

**Issue by alanlowzies** [nus-cs2113-AY2122S2/forum#21]
Hi there, I would like to seek clarification on the behaviour of our iP chatbot program when adding tasks.

In [Week 3](https://nus-cs2113-ay2122s2.github.io/website/schedule/week3/project.html#2-add-increments-commit-tag-push-level-1-level-2-level-3-a-codingstandard), we programmed our chatbots to add any text entered by the user to its list (as long as the text is not "list" or "bye"), and in [Week 4](https://nus-cs2113-ay2122s2.github.io/website/schedule/week4/project.html#2-add-increments-level-4-a-textuitesting-a-codequality), we are adding three new specific types of tasks for the user to specify.

I was wondering with the addition of the three specific task types, does this mean that any text without the appropriate 'command' will now be considered an error? For example, now that we have `todo read book`, is `read book` without the `todo` command now an invalid command?

Thank you in advance 🙂

**Comment by okkhoy** [comment]
There is no one-way-to-do-it! It depends on how you want to implement it.

E.g., 
`read book` could be added as a todo (without explicit keyword todo)
`read book by 21-02-2022` could be a deadline (deciphering from the sentence format, again no explicit keyword)
OR
`todo read book` - explicitly stated as todo
`deadline read book by 21-02-2022` - explicitly stated deadline

Following the first route is a bit more work to identify what is potentially being added whereas the second option is clear cut.
Accordingly, your error handling mileage varies.

**Comment by alanlowzies** [comment]
Alright, thanks for the advice, prof! I'll mull over my implementation 🙂
