### ISSUE TITLE
sourcetree push error again

### ISSUE THREAD

**Issue by Yzkkk** [nus-cs2113-AY2122S2/forum#22]
hi, last time i was able to successfully push but today it suddenly ask me login (which i did using personal access token) but still unable to push.
![Screenshot (596)](https://user-images.githubusercontent.com/69583592/152110947-3263ae31-e27e-41e7-b5c8-8ab577fe7d58.png)
![Screenshot (597)](https://user-images.githubusercontent.com/69583592/152110989-e0eecd25-c05f-4aea-9a58-133321d84e64.png)

**Comment by okkhoy** [comment]
Strangely, it seems like this can happen when you have an outdated git version. Please check [this link](https://community.atlassian.com/t5/Bitbucket-questions/Error-Logon-failed-use-ctrl-c-to-cancel-basic-credential-prompt/qaq-p/1540433) for instructions.

**Comment by Yzkkk** [comment]
![Screenshot (599)_LI](https://user-images.githubusercontent.com/69583592/152114748-5cd263cd-f175-4c56-bd7f-de952a323baa.jpg)

**Comment by okkhoy** [comment]
Hmmm strange.. seems to work for me.
![image](https://user-images.githubusercontent.com/1023494/152121106-2870b042-49e4-405f-be4a-737bd523a127.png)

1. Are you using WSL? If so, try [this link](https://www.bytesized.xyz/how-to-update-git-in-ubuntu-windows-subsystem-for-linux/).
2. Are you using the git that is bundled with sourcetree (embedded git)?  If so, go to Sourcetree -> Tools -> Options -> Git -> Git version -> Update Embedded. 
![image](https://user-images.githubusercontent.com/1023494/152121795-168394e8-e19c-496c-b7d9-4615dfe4f3ad.png)

**Comment by okkhoy** [comment]
@Yzkkk 
Was the problem solved? If so, can you please summarize the issue and what solved the problem? It would help the others who may face similar issues.

**Comment by Yzkkk** [comment]
I tried the second method and the credential helper window still pops out when I tried to push, and after I selected "wincred" it seemed to work somehow. I suppose the credential helper is not supposed to appear, but eventually, it still worked without giving errors.

**Comment by okkhoy** [comment]
I see. Thanks for the update.
Git started using a new credential helper/store in the recent past. I suppose these are the after-effects.
