### ISSUE TITLE
Re-tagging A-CodeQuality

### ISSUE THREAD

**Issue by FaliciaOng** [nus-cs2113-AY2122S2/forum#24]
After reading the comments from my peers today, am I allowed to change my code, re-tag it under A-CodeQuality and push to git?

**Comment by okkhoy** [comment]
Yes, you are allowed to do it. Github doesn't allow you to use the same tag again; so you can name the new tag A-CodeQuality-v2 or something (just please ensure that A-CodeQuality is present in the name).

**Comment by FaliciaOng** [comment]
alright, Thanks for the clarification!
