### ISSUE TITLE
IP Commit Messages

### ISSUE THREAD

**Issue by siewyangzhi** [nus-cs2113-AY2122S2/forum#26]
Hi prof,

For the level 4 commit, I have added the functionalities of level 4 as well as having rearranged some of my functions by placing it into a new class called decoder as well as a superclass called command which has subclass for each type of command such as add new task. Thus for the commit message, this is all I am able to write due to the java convention of the commit message subject having a hard limit of 72 words. Is the above commit message sufficient or do I require further elaboration?

![git commit message](https://user-images.githubusercontent.com/69446719/152524342-5c276f11-e67e-49bc-88ce-fceb59ea307f.PNG)

**Comment by okkhoy** [comment]
TL;DR:
This should do.

Long form:
You could choose to add more details in the "commit message body". Just add a blank line between the first line (which acts as header and appears on GitHub) and the rest of the message where you can add details.
E.g., (in the context of Lecture 4)

```
Improve code organization

Create package circus and move all java under the circus package.
Create package circus.animal and move all animal-related files to it
Update runtest.bat/runtest.sh commands to reflect the new package structure
```

Here `Improve code organization` appears in the heading, rest of it appears as commit message body.

**Comment by siewyangzhi** [comment]
I see thank you
