### ISSUE TITLE
Utility Classes

### ISSUE THREAD

**Issue by shxr3f** [nus-cs2113-AY2122S2/forum#3]
What is the best practice if you want to create a helper class that only has static methods that you might call often. For example a certain decoration (i.e dotted line) that you might print often, is it a good practice to create a helper class of decorations that only has static methods that print out various decorations you might use?

**Comment by okkhoy** [comment]
You can have classes with only static methods. There is no rule against it. However, when we learn about coupling/patterns you will see why static (edit: read as static data items) is not always the best thing.

**Comment by shxr3f** [comment]
Oh alright, thanks very much for the input.
