### ISSUE TITLE
Is it absolutely necessary to include exceptions when it introduces way more LOC?

### ISSUE THREAD

**Issue by BradenTeo** [nus-cs2113-AY2122S2/forum#31]
I'm referring to Level-5 increment of the iP, where we are expected to use an exception to handle invalid inputs.
![image](https://user-images.githubusercontent.com/58351701/153055599-f45c9567-2f7c-4e83-9fd3-3e7147df8466.png)

In my code, I use a switch block to decide what to do with the inputs (e.g. list, mark, unmark). The default of the switch block will just print out a message similar to the one shown in the picture above. It is very short and I feel that modifying my code to include the exception would reduce the readability by a lot.

The website says that the minimal requirement is to handle the stated types of errors, but I'm hesitant to, and would thus like a second opinion on this. Thank you :)

**Comment by shunyao643** [comment]
How about putting it within a method or as a string constant? 

I think it's important to tell your user what's wrong with their input and how to correct it.

**Comment by okkhoy** [comment]
The exercise requires you to use exceptions. Not sure what you are referring to here?

**Comment by BradenTeo** [comment]
Sorry, I think it is easier to explain with some code.
This code block is in my Main class: 
```java
while (!input.equals("bye")) {            //input refers to the user's input
     String[] arrOfInputStrings = input.split(" ");
     
     switch(arrOfInputStrings[0]) {
     case "list":
           displayList(tasks, taskCounter);
           break;
     //other cases
     default:
           invalid_input();
           break;
     }
     
     input = in.nextLine();
}
```
^So the `invalid_input()` would take care of invalid inputs that are not specific to the different commands. 
(I have done up exceptions for the other commands like list and todo). 

I can't think of a nice way to implement exceptions that wouldn't bloat the code.

**Comment by wli-linda** [comment]
It seems like your `invalid_input()` method already corresponds to the second type of errors that should be handled? 
As for the first type of error-handling required for `Level-5`, which catches the case where no descriptions supplied for Todo commands, couldn't you just implement it within the "todo" case of your switch statement? And if you're worried about code quality, you can always consider refactoring your code by extracting a method from the "todo" case.

**Comment by BradenTeo** [comment]
Yep, that's what I did. Thanks for all your suggestions. I'll mark this thread as resolved now.
