### ISSUE TITLE
GitHub not allowing me to upload a JAR file as a release

### ISSUE THREAD

**Issue by zhengster** [nus-cs2113-AY2122S2/forum#33]
I've created the JAR file for the "A-Jar" increment of the ip, but when I try to make a release in GitHub and drag the JAR file in, GitHub is complaining that it doesn't support that file type. I'm pretty certain I followed the steps to create the JAR file correctly; I included some screenshots of Intellij, my file explorer, and the GitHub error message. 
![image](https://user-images.githubusercontent.com/20442226/153743027-102d7b8a-9e46-4c3a-b82e-cbb2fbb0c892.png)
![image](https://user-images.githubusercontent.com/20442226/153743058-79e0bb1a-c3e0-4832-841c-b5dadd295562.png)
![image](https://user-images.githubusercontent.com/20442226/153742981-3ee8136b-300f-4a1c-9bd5-289683d1db68.png)

**Comment by okkhoy** [comment]
Looks like you are trying to attach the JAR file to the release message.
There should be another part below the message field where you can attach it.

**Comment by zhengster** [comment]
Thanks!
