### ISSUE TITLE
runtest.sh file not working

### ISSUE THREAD

**Issue by BradenTeo** [nus-cs2113-AY2122S2/forum#34]
Hi, I'm having some trouble running the runtest.sh file.
After editing the runtest.sh and runtest.bat files as shown in Week 4's lecture, I still encountered this error.
![image](https://user-images.githubusercontent.com/58351701/153899904-bd857bc2-3aa2-421f-9db7-f5272e002950.png)

My file tree is as shown:
![image](https://user-images.githubusercontent.com/58351701/153900680-2087decc-5c4e-4bd1-96ec-4846d6fc4fea.png)

And these are the parts I edited in my runtest.sh file:
```java
if ! javac -cp ../src/main/java -Xlint:none -d ../bin ..\src\main\java\alexis\exceptions\*.java ..\src\main\java\alexis\main\*.java ..\src\main\java\alexis\task\*.java
then
    echo "********** BUILD FAILURE **********"
    exit 1
fi
```
```java
java -classpath ../bin alexis.main.Main < input.txt > ACTUAL.TXT
```

Did I miss out something somewhere?

**Comment by okkhoy** [comment]
If you are using the `runtest.sh` (**shell**) file:

`\src\main\java\alexis\exceptions\*.java` should be `/src/main/java/alexis/exceptions/*.java`

**Comment by BradenTeo** [comment]
Ohh, it works.
So if I use .sh, it is "/" and if I use .bat it is "\\". Thank you!
