### ISSUE TITLE
Merging conflicts

### ISSUE THREAD

**Issue by botbw** [nus-cs2113-AY2122S2/forum#37]
Let's say I implemented a new feature on branch-A, and now I want to add the feature to the main branch.
Should I:
a) switch to branch-A, merge the main branch, resolve the conflicts, switch to the main branch, merge the branch-A.
or
b) switch to the main branch, merge branch-A, resolve the conflicts.

**Comment by okkhoy** [comment]
If you are creating a PR to manage the merge, a) is better, except that you will create a PR from branch-A rather than merge branch-A to master directly. If you are simply merging on your local without affecting others, you can do either of them
