### ISSUE TITLE
If Else Statements

### ISSUE THREAD

**Issue by siewyangzhi** [nus-cs2113-AY2122S2/forum#38]
Hi, it was mentioned that when we are checking to see if a variable is value A or Value B, we shouldn't do 
if (variable == value A) {
//Do something
}else{
// Assuming that the variable is value B and do something.
}
I get that the rationale for doing this is because the variable can hold more than 2 values thus we cant assume that if it isnt value A, it would be value B.

![image](https://user-images.githubusercontent.com/69446719/155670480-39043dea-523b-4e0f-bd6f-8484527b3aa4.png)

However, for my case above , i am checking the value of a boolean thus can i use the if statement to check if the boolean is true and for the else statement, i would assume it is false since it can only take on two values.

**Comment by okkhoy** [comment]
You have answered your own question -- When do you need an explicit else? 
So for boolean, what you have is correct.

**Comment by siewyangzhi** [comment]
I see thank you
