### ISSUE TITLE
Combining Refactoring and Level - 9

### ISSUE THREAD

**Issue by siewyangzhi** [nus-cs2113-AY2122S2/forum#39]
I have refactored my code to make it more OOP before committing and marking it with the A-MoreOOP tag. However, while doing the Level-9 increment, I refactored some portion of my code not previously refactored to make it more OOP.

Thus, can I add this refactor under the Level - 9 increment since i have already done the bulk of the refactoring previously and tagged it as  A-MoreOOP.

**Comment by okkhoy** [comment]
Yes, you can do that

**Comment by siewyangzhi** [comment]
I see thank you
