### ISSUE TITLE
Possible inconsistent formatting for Coursemology Week 3 Question 10

### ISSUE THREAD

**Issue by zhengster** [nus-cs2113-AY2122S2/forum#4]
I'm trying to match the formatting of my code output to the problem description. As seen from the description, there seems to be a line break after every line printed in the output (i.e. new lines to begin "Your expenses while overseas," "Expenses in overseas currency," and "Total in local currency"). 
![image](https://user-images.githubusercontent.com/20442226/150667150-22110c54-3f75-455d-9e4b-9d40443230d2.png)
However, this is not reflected in the Coursemology expected output. For the second input, the expected output does not have a new line to begin the "Total in local currency" line. So, which format should we be adhering to: Coursemology's or the CS2113 website's? Also, I'm not sure why my result for the first input is being marked as incorrect...
![image](https://user-images.githubusercontent.com/20442226/150667249-a277684f-b994-4f0a-b3b9-21364dfc00b1.png)
Thanks!

**Comment by okkhoy** [comment]
@Mick609 @shivin9 please take a look and help @zhenster with the coursemology exercise.

**Comment by shivin9** [comment]
@zhenster can you share how you are writing the print statement?

**Comment by zhengster** [comment]
Sure - here are my print statements. (The helper methods extractPrices() and calculateTotal() do not return any new line characters; all the newline characters are from the "System.out.println" calls). 
```  
 public static void main(String[] args) {
        String line;
        Scanner in = new Scanner(System.in);

        System.out.print("Your expenses while overseas?");
        String expenses = extractPrices(in.nextLine()); 
        System.out.println("Expenses in overseas currency: " + expenses); 
        System.out.println("Total in local currency: " + calculateTotal(expenses)); 

    }
```  
Thanks for your help!

**Comment by jltha** [comment]
The text formatting in both coursemology and the website should be the same. Perhaps you can look through your code in coursemology, and see if you missed out any code which you did not copy. I encountered the same error when I forgot to import the relevant libraries. Hope this helps.

**Comment by shivin9** [comment]
Try changing ```...println -> ...print```. It seems that there is no ```\n``` in the expected output.

**Comment by zhengster** [comment]
If I try changing from println to print, then the formatting is fixed for the second input but is incorrect for the first. 
![image](https://user-images.githubusercontent.com/20442226/150678371-6fc1d012-e2ac-4dc8-9e22-01ef6789b7b4.png)
I suppose I could hard-code it so that the formatting is dependent on the input, but I think that might be frowned upon. 😂 Perhaps there is an issue with the test cases themselves?

**Comment by eigne** [comment]
You need to remove the space at the end of "Expenses in overseas currency: " and avoid println for both. My code looks like yours but with those two changes it manages to pass both test cases. 

edit: "Total in local currency: " should retain the space at the end though.

**Comment by zhengster** [comment]
That worked, thank you!
