### ISSUE TITLE
Packages not found during Text UI Testing

### ISSUE THREAD

**Issue by tanweili** [nus-cs2113-AY2122S2/forum#41]
I was trying to run the runtest.bat to try testing my current ip which has many packages. I tried updating the runtest.bat file according to the [link](https://se-education.org/guides/tutorials/textUiTesting.html) provided but the test is unable to find my packages. May I know how do I update the .bat file correctly?
![SS](https://user-images.githubusercontent.com/69900891/156324010-38c3f2f0-fb04-4370-89bc-59232317d660.jpg)

**Comment by okkhoy** [comment]
Your line 10 in `runtest.bat` is only compiling Duke.java. You are not compiling all other things.
Update that accordingly, and it should work.

**Comment by tanweili** [comment]
So if my Duke.java is currently within a duke package, that line of code should be
`javac  -cp ..\src\main\java\duke -Xlint:none -d ..\bin\duke ..\src\main\java\duke\Duke.java` ?
Is `-cp ..\src\main\java\duke` the path to the file I want to compile?
I suppose `..\bin\duke` is the output folder that I want to put the file at?
`-Xlint:none` is this necessary?
`..\src\main\java\duke\Duke.java` this line of code references the file I want to compile itself?
Also do I need to compile all my other packages first before compiling the main Duke.java?

**Comment by okkhoy** [comment]
Hmmm... I had covered all of this in the lecture when we did hands-on on packages. 
Did you get a chance to try it out then? Or view the recording later (Lecture 4; around 1hr 35 min mark)?

**Comment by tanweili** [comment]
I didn't try it out then. Will view the recording later!
