### ISSUE TITLE
Publishing of user guide issue

### ISSUE THREAD

**Issue by FaliciaOng** [nus-cs2113-AY2122S2/forum#42]
When I publish my user guide, I did a command summary table which display perfectly fine on github. However, When i tried to test it on http://{your username}.github.io/{repo name}/ , the formatting gets messed up. Is there a reason why it would get messed up? How can i solve this.

![image](https://user-images.githubusercontent.com/69444353/156336140-9097d827-dc32-4e2a-b7d9-ea7a0753d3df.png)

**Comment by okkhoy** [comment]
You need an additional new line between the header and the rest of the table.
