### ISSUE TITLE
Editing Checkstyle for tP

### ISSUE THREAD

**Issue by BradenTeo** [nus-cs2113-AY2122S2/forum#46]
We noticed that if we extend a line of code to the next line and include 8 spaces, a checkstyle error occurs. 

We changed all our spacings to 4 in one of our PRs but we would like to ask how should we go from here.
![image](https://user-images.githubusercontent.com/58351701/157589555-c7e0f302-e392-426f-9f29-e5f07be1ce10.png)

Is there a need to edit the checkstyle.xml file?

**Comment by okkhoy** [comment]
see #47
