### ISSUE TITLE
IP evaluation

### ISSUE THREAD

**Issue by XunyiiZ** [nus-cs2113-AY2122S2/forum#48]
i try to access jar file in cmd using: java -jar Duke
but it shows an error like this. this is the problem from my end or is it the problem of the file?

![image](https://user-images.githubusercontent.com/73570047/157787485-805bb863-ae74-48dc-b65a-a648678c5ab2.png)

**Comment by okkhoy** [comment]
please drop me an email with a complete screenshot (not just the error message)
