### ISSUE TITLE
Issues with Gradle Checking regarding constants.

### ISSUE THREAD

**Issue by siewyangzhi** [nus-cs2113-AY2122S2/forum#52]
Hi prof, there seems to be some issue with the checks run by Gradle as it does not accept the naming convention specified in this module for constants as seen in the picture below.

![image](https://user-images.githubusercontent.com/69446719/158077523-ca635425-c8bd-41e3-a4e6-1acbb6d318b6.png)

**Comment by siewyangzhi** [comment]
The issue has been resolved. The error was due to the fact that I did not include static for my constants.

**Comment by okkhoy** [comment]
Good that it got resolved! I was trying to re-create the issue and it didn't error out for me. So I had paused on this until my lecture later in the evening completes :-) 
Thanks for updating it!
