### ISSUE TITLE
Recover tracking history and branches in sourcetree

### ISSUE THREAD

**Issue by jltha** [nus-cs2113-AY2122S2/forum#55]
My laptop crashed out of nowhere as I was about to commit in sourcetree. After the reboot, I realised the history of all commits and my branches in sourcetree are gone. Below is the error message I get when I open sourcetree, as well as when I try to pull any code from my remote/team repo

![dsadsa](https://user-images.githubusercontent.com/69579839/159497758-5d48dc55-ed11-45ab-af05-4f9e8f7b75d4.JPG)
![image](https://user-images.githubusercontent.com/69579839/159545188-fca458c7-4a65-47ec-bec7-38a2f7e5312e.png)

Below is a screenshot of my current sourcetree status when I open it:

![image](https://user-images.githubusercontent.com/69579839/159498000-bf3bfa00-4c82-42c5-8626-d7b16dc93299.png)

Appreciate any help and/or advice on how to restore my settings.

**Comment by okkhoy** [comment]
Answered via chat!
