### ISSUE TITLE
Error when putting PlantUML object diagram in DeveloperGuide markdown file 

### ISSUE THREAD

**Issue by zhengster** [nus-cs2113-AY2122S2/forum#56]
I am experiencing some difficulties with integrating a PlantUML object diagram in my Developer Guide markdown file. In the md file, when I try to insert a PlantUML diagram field like so: 
```plantuml 
@startuml
object Duke
object SatisfactionList
@enduml
```
I get the following error: 
![image](https://user-images.githubusercontent.com/20442226/159616267-e8ee7c4a-ba0f-49f2-8269-30bdea954756.png)
I have followed all the instructions here (https://se-education.org/guides/tutorials/plantUml.html): I've downloaded GraphViz and configured the path to the dot executable in `Settings` > `Languages & Frameworks` > `PlantUML`. I'm not sure why the dot executable is not being found.

**Comment by okkhoy** [comment]
I think you need to add the path to plantuml to the the system path
