### ISSUE TITLE
JUnit Test for System.out

### ISSUE THREAD

**Issue by shxr3f** [nus-cs2113-AY2122S2/forum#57]
![image](https://user-images.githubusercontent.com/77721568/159665376-bbbc753d-c7de-4c3f-9ec9-918c37bd22cb.png)
The above image is a test that checks what was printed out on the console when the mentioned method is called. This test case passes on ubuntu os, however there is a need to include a "\r" in front of every "\n" (see image below) when running the tests on windows for the same test to pass. 
![image](https://user-images.githubusercontent.com/77721568/159665967-5a409474-c2ce-4ecf-9564-2e83f3219c32.png)
How do I deal with this issue?

**Comment by okkhoy** [comment]
Will wait for someone to answer 🙂

**Comment by jltha** [comment]
You can try replacing `\n` with `System.lineSeparator()`. It worked for me.

**Comment by shxr3f** [comment]
> You can try replacing `\n` with `System.lineSeparator()`. It worked for me.

Oh right, will try it out thanks!!
