### ISSUE TITLE
Editing User Guide after submission

### ISSUE THREAD

**Issue by BradenTeo** [nus-cs2113-AY2122S2/forum#66]
Hi Prof/tutors, suppose we identify some improvements to make for our UG in the coming days, are we allowed to edit it? I know by right it's not allowed for CS2113/T, but for the CS2101 side, the deadline for UG submission is only this Friday.

Thank you.

**Comment by okkhoy** [comment]
Let's stick to this published guideline:
![image](https://user-images.githubusercontent.com/1023494/162879627-a682f06b-87a3-4e1f-b8a4-a09213258a06.png)
So maybe tomorrow you can update?

**Comment by BradenTeo** [comment]
Ohh, I didn't see that. Thank you, prof.
