### ISSUE TITLE
Accessing the CS2113 github.io website during PE

### ISSUE THREAD

**Issue by siewyangzhi** [nus-cs2113-AY2122S2/forum#67]
Hi prof, 

Are we allowed to access the CS2113 github.io website to reference the lecture notes during the PE examinations?

**Comment by okkhoy** [comment]
Yup:
![image](https://user-images.githubusercontent.com/1023494/163519104-6b02cbe8-3240-44e0-971f-05aa9cbdf3e1.png)

**Comment by siewyangzhi** [comment]
Understand thank you

**Comment by siewyangzhi** [comment]
Hi Prof,
Just to confirm, are we allowed to have with us a hardcopy piece of paper so that we can jot down the types of commands we would be trying beforehand such as empty fields in the command so that we have sort of planned out the sequence of the test beforehand in that sense.
