### ISSUE TITLE
Not able to assign the issues to users

### ISSUE THREAD

**Issue by shxr3f** [nus-cs2113-AY2122S2/forum#69]
I am not able to assign the issues to anyone for the Developer Response part of the PE. It always throws an error saying user is not authorised. Do help with this issue.

![image](https://user-images.githubusercontent.com/77721568/163702199-6e625d38-bcca-46b6-a6d7-10e91bad59d9.png)

**Comment by siewyangzhi** [comment]
It is being rectified by the devlopers as per https://github.com/CATcher-org/CATcher/issues/925

**Comment by shxr3f** [comment]
Oh great will follow through on that issue then!

> It is being rectified by the devlopers as per [CATcher-org/CATcher#925](https://github.com/CATcher-org/CATcher/issues/925)
