### ISSUE TITLE
Unable to locate src folder of ip in Intellij

### ISSUE THREAD

**Issue by zhengster** [nus-cs2113-AY2122S2/forum#7]
This is probably something very small/dumb, but for some reason I am unable to locate my src folder in Intellij. It's definitely in my file explorer (along with the docs and text-ui-test folders), but it's not showing up in the sidebar in Intellij. 
![image](https://user-images.githubusercontent.com/20442226/150789064-851e95b9-6fdc-477e-bab5-b8982ac328cb.png)
Here's what my file explorer looks like: 
![image](https://user-images.githubusercontent.com/20442226/150789119-88332665-ef4c-4399-81fe-8a88969514e9.png)
I was definitely able to locate the src folder last week when I completed Duke Level-0, but I am no longer able to see it. I also tried deleting my old project (the local cloned copy as well as the repository in github) and simply re-doing the set-up, but I unfortunately ran into the same issue. If it helps, here are the contents of my .gitignore. 
![image](https://user-images.githubusercontent.com/20442226/150789410-ff2c708e-0d0a-48ba-8ad1-09d5ed7d7c12.png)
Thanks!

**Comment by eigne** [comment]
The .idea folder should be visible in the same folder as docs, src and the rest though. Can you post a screenshot of your explorer window with the full path visible?
![image](https://user-images.githubusercontent.com/60597985/150800478-7681be6b-0f76-44d0-934f-0bbb7126c483.png)

I tried making a copy of my ip folder and deleting the .idea folder so it only contains the folders/files in your screenshot. From there I used File -> Open to open the copied folder as a new project and IntelliJ created a new .idea folder inside it. Everything seems to work fine with the copied project.

**Comment by zhengster** [comment]
Here's my screenshot of the whole file path. 
![image](https://user-images.githubusercontent.com/20442226/150891217-39b2d3f9-6965-4ba6-98b4-74696bda10c0.png)
It's strange because the .idea folder isn't even in the same level as docs, src, etc (I searched through the existing folders and it seems like .idea isn't even there). I definitely didn't remove or change anything; this was cloned directly from the nus-cs2113-AY2122S2/ip folder. I tried making a copy and opening the copied folder, but that also didn't work.

**Comment by okkhoy** [comment]
Looks like your import is a bit messed up (possibly).
Close the project in IntelliJ and close IntelliJ.
Find where the .idea folder is (is it inside src or one of the subfolders?), and delete it.
Open IntelliJ and import the project afresh. Ensure that you select the iP directory and not inside that.
That should fix the problem, and you should be able to run the project (once the JDK is setup).

**Comment by zhengster** [comment]
I tried to find the .idea folder in my file explorer but I couldn't find it...I looked through all the subfolders as well. What do you recommend I do? I've already tried deleting the project entirely and doing the fork/cloning process again, as well as copying the project, but I still got the same broken file structure.

**Comment by okkhoy** [comment]
Ping me on MSTeams? Let's try to work it out together.
