### ISSUE TITLE
Level 3: Should entering the same text more than once result in multiple tasks being added or just one?

### ISSUE THREAD

**Issue by eigne** [nus-cs2113-AY2122S2/forum#8]
Should my code check for duplicate task descriptions and avoid storing more than one of the same task? Should a scenario like this be possible?

list
    ____________________________________________________________
     Here are the tasks in your list:
     1.[X] read book
     2.[ ] read book
     3.[ ] buy bread

**Comment by okkhoy** [comment]
At the moment you can choose not to do that. You can think about it when you implement exception handling later.

**Comment by eigne** [comment]
Thank you.
